// Generated by scripts/filmsim_bake.py — do not edit by hand.
// Ordered film/paper stocks for the spectral film simulation, plus the
// precomputed neutral enlarger balance per film×paper (optimised for this pipeline).
import simd

/// Anti-halation layer class from the film's datasheet profile. Weak layers
/// (consumer C41 stocks) show the classic red-orange glow; strong layers and
/// remjet-backed cine stocks stay clean; `no` is the uncoated look.
public enum Antihalation: String, Sendable, Hashable {
    case strong, weak, no
}

/// One selectable emulsion. `index` is the value handed to the kernel:
/// `film` (0..<paperOffset) for films, relative 0-based `paper` for papers.
public struct FilmStock: Sendable, Hashable, Identifiable {
    public let index: Int
    public let key: String
    public let name: String
    public let isPaper: Bool
    /// Reversal (slide) stock — best viewed via the scanned-positive path, not an RA4 print.
    public let isPositive: Bool
    /// Films: anti-halation class from the profile. Papers: always `.strong`.
    public let antihalation: Antihalation
    /// The profile's companion print stock (`target_print`), if any.
    public let targetPaperKey: String?
    public var id: String { (isPaper ? "paper:" : "film:") + key }
}

public enum FilmSimData {
    /// First paper's row block in FilmSim.lut; equals the film count.
    public static let paperOffset = 20

    public static let films: [FilmStock] = [
        FilmStock(index: 0, key: "kodak_ektar_100", name: "Kodak Ektar 100", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_portra_endura"),
        FilmStock(index: 1, key: "kodak_portra_160", name: "Kodak Portra 160", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_portra_endura"),
        FilmStock(index: 2, key: "kodak_portra_400", name: "Kodak Portra 400", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_portra_endura"),
        FilmStock(index: 3, key: "kodak_portra_800", name: "Kodak Portra 800", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_portra_endura"),
        FilmStock(index: 4, key: "kodak_portra_800_push1", name: "Kodak Portra 800 (Push 1)", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_portra_endura"),
        FilmStock(index: 5, key: "kodak_portra_800_push2", name: "Kodak Portra 800 (Push 2)", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_portra_endura"),
        FilmStock(index: 6, key: "kodak_gold_200", name: "Kodak Gold 200", isPaper: false, isPositive: false, antihalation: .weak, targetPaperKey: "kodak_portra_endura"),
        FilmStock(index: 7, key: "kodak_ultramax_400", name: "Kodak Ultramax 400", isPaper: false, isPositive: false, antihalation: .weak, targetPaperKey: "kodak_portra_endura"),
        FilmStock(index: 8, key: "kodak_vision3_50d", name: "Kodak Vision3 50D", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_2383"),
        FilmStock(index: 9, key: "kodak_vision3_250d", name: "Kodak Vision3 250D", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_2383"),
        FilmStock(index: 10, key: "kodak_vision3_200t", name: "Kodak Vision3 200T", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_2383"),
        FilmStock(index: 11, key: "kodak_vision3_500t", name: "Kodak Vision3 500T", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_2383"),
        FilmStock(index: 12, key: "fujifilm_pro_400h", name: "Fujifilm Pro 400H", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "fujifilm_crystal_archive_typeii"),
        FilmStock(index: 13, key: "fujifilm_xtra_400", name: "Fujifilm X-Tra 400", isPaper: false, isPositive: false, antihalation: .weak, targetPaperKey: "fujifilm_crystal_archive_typeii"),
        FilmStock(index: 14, key: "fujifilm_c200", name: "Fujifilm C200", isPaper: false, isPositive: false, antihalation: .weak, targetPaperKey: "fujifilm_crystal_archive_typeii"),
        FilmStock(index: 15, key: "kodak_ektachrome_100", name: "Kodak Ektachrome 100", isPaper: false, isPositive: true, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 16, key: "kodak_kodachrome_64", name: "Kodak Kodachrome 64", isPaper: false, isPositive: true, antihalation: .weak, targetPaperKey: nil),
        FilmStock(index: 17, key: "fujifilm_provia_100f", name: "Fujifilm Provia 100F", isPaper: false, isPositive: true, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 18, key: "fujifilm_velvia_100", name: "Fujifilm Velvia 100", isPaper: false, isPositive: true, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 19, key: "kodak_verita_200d", name: "Kodak Verita 200D", isPaper: false, isPositive: false, antihalation: .strong, targetPaperKey: "kodak_2383"),
    ]

    public static let papers: [FilmStock] = [
        FilmStock(index: 0, key: "kodak_endura_premier", name: "Kodak Professional Endura Premier", isPaper: true, isPositive: false, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 1, key: "kodak_ektacolor_edge", name: "Kodak Ektacolor Edge", isPaper: true, isPositive: false, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 2, key: "kodak_supra_endura", name: "Kodak Professional Supra Endura", isPaper: true, isPositive: false, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 3, key: "kodak_portra_endura", name: "Kodak Professional Portra Endura", isPaper: true, isPositive: false, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 4, key: "fujifilm_crystal_archive_typeii", name: "Fujifilm Crystal Archive Type II", isPaper: true, isPositive: false, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 5, key: "kodak_2383", name: "Kodak Vision 2383", isPaper: true, isPositive: false, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 6, key: "kodak_2393", name: "Kodak Vision Premier 2393", isPaper: true, isPositive: false, antihalation: .strong, targetPaperKey: nil),
        FilmStock(index: 7, key: "kodak_ultra_endura", name: "Kodak Professional Ultra Endura", isPaper: true, isPositive: false, antihalation: .strong, targetPaperKey: nil),
    ]

    /// Neutral balance per [film][paper]: (printEV, filterC, filterM, filterY).
    static let neutralWB: [[SIMD4<Float>]] = [
        [SIMD4<Float>(0.39803, 0.00697432, 0.698293, 0.457622), SIMD4<Float>(1.04526, 0.310774, 0.788966, 0.641373), SIMD4<Float>(0.498578, 0.0296082, 0.70749, 0.502425), SIMD4<Float>(0.937782, 0.250444, 0.769167, 0.622138), SIMD4<Float>(1.23292, 0.0284339, 0.813875, 0.715462), SIMD4<Float>(3.53852, 0.682207, 0.913226, 0.857062), SIMD4<Float>(1.97846, 0.121949, 0.784152, 0.609937), SIMD4<Float>(0.502256, 0.0737067, 0.694722, 0.462008)],
        [SIMD4<Float>(0.0969084, 5.4363e-06, 0.59286, 0.377621), SIMD4<Float>(0.0960875, 0.000202728, 0.586329, 0.382015), SIMD4<Float>(0.109771, 0.000210438, 0.587176, 0.391185), SIMD4<Float>(0.10977, 1.02844e-06, 0.584507, 0.389781), SIMD4<Float>(0.90183, 0.000135684, 0.745173, 0.654073), SIMD4<Float>(1.48655, 0.001507, 0.697804, 0.508214), SIMD4<Float>(1.54092, 0.0889171, 0.68732, 0.541473), SIMD4<Float>(0.280726, 0.109249, 0.60526, 0.412567)],
        [SIMD4<Float>(-0.348205, 0.00368367, 0.425591, 0.273585), SIMD4<Float>(-0.416533, 0.0036123, 0.392755, 0.246741), SIMD4<Float>(-0.00372625, 0.223349, 0.509868, 0.416549), SIMD4<Float>(-0.00704446, 0.221573, 0.505808, 0.414043), SIMD4<Float>(0.417102, 0.000761612, 0.630547, 0.577103), SIMD4<Float>(0.991025, 3.6471e-06, 0.562216, 0.397831), SIMD4<Float>(0.955581, 0.00596509, 0.529251, 0.405807), SIMD4<Float>(-0.00255224, 0.189345, 0.489003, 0.379365)],
        [SIMD4<Float>(0.328389, 0.000946798, 0.636042, 0.545786), SIMD4<Float>(0.353099, 0.000251382, 0.635766, 0.554263), SIMD4<Float>(0.375045, 3.42323e-06, 0.637495, 0.566154), SIMD4<Float>(0.4192, 0.0245404, 0.643809, 0.5769), SIMD4<Float>(1.19558, 0.0292166, 0.784178, 0.757096), SIMD4<Float>(1.67537, 2.40543e-07, 0.724729, 0.61709), SIMD4<Float>(1.55576, 0.000633066, 0.690144, 0.594332), SIMD4<Float>(0.31705, 0.00179405, 0.607489, 0.516106)],
        [SIMD4<Float>(0.627789, 0.00115681, 0.653895, 0.522928), SIMD4<Float>(0.838487, 0.107421, 0.687522, 0.582841), SIMD4<Float>(0.667097, 0.00331534, 0.65394, 0.542945), SIMD4<Float>(1.48694, 0.383835, 0.780966, 0.727399), SIMD4<Float>(1.48376, 0.0295647, 0.792588, 0.746615), SIMD4<Float>(3.14745, 0.525142, 0.861098, 0.810257), SIMD4<Float>(1.87367, 0.000180584, 0.710928, 0.574874), SIMD4<Float>(0.873327, 0.14345, 0.67598, 0.566921)],
        [SIMD4<Float>(1.08711, 0.149874, 0.709041, 0.602346), SIMD4<Float>(0.856882, 0.0181399, 0.663994, 0.541526), SIMD4<Float>(0.842551, 1.68456e-05, 0.659559, 0.54506), SIMD4<Float>(0.850905, 0.00437403, 0.658886, 0.546353), SIMD4<Float>(2.7499, 0.506378, 0.893807, 0.873229), SIMD4<Float>(2.26156, 0.0480449, 0.760777, 0.623352), SIMD4<Float>(2.07709, 0.000123049, 0.721687, 0.583203), SIMD4<Float>(0.807831, 0.00292735, 0.636071, 0.498815)],
        [SIMD4<Float>(0.0414827, 0.000204804, 0.526802, 0.37614), SIMD4<Float>(-0.0180825, 0.000777726, 0.503808, 0.352586), SIMD4<Float>(-0.04907, 0.00251235, 0.493408, 0.349912), SIMD4<Float>(0.00154115, 0.0301918, 0.503201, 0.368352), SIMD4<Float>(0.807827, 0.00572027, 0.692868, 0.655576), SIMD4<Float>(1.37174, 0.000706551, 0.635059, 0.45614), SIMD4<Float>(1.32836, 2.63934e-05, 0.611509, 0.450707), SIMD4<Float>(0.0301363, 8.90155e-05, 0.49163, 0.336087)],
        [SIMD4<Float>(-0.0378796, 0.00135525, 0.525805, 0.412325), SIMD4<Float>(0.385232, 0.244726, 0.617137, 0.548464), SIMD4<Float>(-0.137316, 0.00143073, 0.486382, 0.384121), SIMD4<Float>(-0.13741, 0.00110047, 0.483048, 0.382735), SIMD4<Float>(0.71591, 0.00110696, 0.693469, 0.666482), SIMD4<Float>(1.30362, 0.00208973, 0.639967, 0.49973), SIMD4<Float>(1.26013, 9.94108e-06, 0.614287, 0.496908), SIMD4<Float>(1.04417, 0.48193, 0.724001, 0.685358)],
        [SIMD4<Float>(-0.759561, 0.137747, 0.283403, 0.179718), SIMD4<Float>(-1.04334, 0.213003, 0.146657, 0.0155736), SIMD4<Float>(-1.08961, 0.266961, 0.11404, 9.83702e-05), SIMD4<Float>(-0.0143091, 0.607964, 0.493904, 0.482413), SIMD4<Float>(-0.661942, 0.208246, 0.276374, 0.325279), SIMD4<Float>(0.378261, 0.000731575, 0.369375, 0.208061), SIMD4<Float>(0.425466, 0.000505776, 0.371493, 0.247898), SIMD4<Float>(-0.8578, 0.0933629, 0.198287, 0.0818749)],
        [SIMD4<Float>(-0.983466, 0.0371053, 0.205487, 0.00188398), SIMD4<Float>(-0.0372201, 0.574358, 0.505978, 0.438199), SIMD4<Float>(0.0957999, 0.646204, 0.530614, 0.486716), SIMD4<Float>(-0.977447, 0.333878, 0.163584, 0.000535494), SIMD4<Float>(-0.0368021, 0.483648, 0.49254, 0.489253), SIMD4<Float>(1.09873, 0.366122, 0.555451, 0.469017), SIMD4<Float>(0.610001, 0.118673, 0.424031, 0.295871), SIMD4<Float>(-0.893947, 0.0939338, 0.191214, 0.0017081)],
        [SIMD4<Float>(-0.266029, 0.545066, 0.392136, 0.00929781), SIMD4<Float>(-0.269514, 0.644339, 0.380074, 0.00126825), SIMD4<Float>(0.19797, 0.756527, 0.507568, 0.26883), SIMD4<Float>(-0.293813, 0.673712, 0.356114, 0.000413985), SIMD4<Float>(0.52393, 0.728513, 0.582387, 0.464481), SIMD4<Float>(0.949535, 0.505219, 0.455041, 0.0827942), SIMD4<Float>(0.792378, 0.442263, 0.409537, 0.00554667), SIMD4<Float>(0.0778544, 0.630895, 0.46021, 0.156853)],
        [SIMD4<Float>(-0.308548, 0.5129, 0.351803, 0.00199271), SIMD4<Float>(-0.0520618, 0.675157, 0.423455, 0.143719), SIMD4<Float>(-0.334375, 0.653994, 0.319937, 0.000295682), SIMD4<Float>(-0.330943, 0.654421, 0.316826, 0.000399085), SIMD4<Float>(-0.53277, 0.470095, 0.199676, 0.0796515), SIMD4<Float>(0.885784, 0.463526, 0.416238, 0.0397279), SIMD4<Float>(0.817644, 0.425767, 0.399729, 0.0080379), SIMD4<Float>(-0.223893, 0.539357, 0.34038, 7.27214e-05)],
        [SIMD4<Float>(-0.155185, 0.237331, 0.416974, 0.0185006), SIMD4<Float>(-0.132921, 0.320731, 0.416553, 0.0294841), SIMD4<Float>(0.167394, 0.461309, 0.488094, 0.206844), SIMD4<Float>(-0.197309, 0.3353, 0.380964, 0.00288197), SIMD4<Float>(0.00241467, 0.0331577, 0.438885, 0.247182), SIMD4<Float>(0.898252, 0.115596, 0.426489, 0.00765819), SIMD4<Float>(0.844728, 0.0892294, 0.40706, 0.00037823), SIMD4<Float>(-0.0108903, 0.301027, 0.423688, 0.0515325)],
        [SIMD4<Float>(0.747718, 0.000457255, 0.695212, 0.671198), SIMD4<Float>(0.635417, 0.0817889, 0.671154, 0.643573), SIMD4<Float>(0.939533, 0.301002, 0.712392, 0.711648), SIMD4<Float>(0.369581, 0.00582624, 0.604121, 0.587593), SIMD4<Float>(1.01097, 0.000644242, 0.72824, 0.758516), SIMD4<Float>(2.4135, 0.207834, 0.78202, 0.768192), SIMD4<Float>(0.717561, 0.0310137, 0.648199, 0.963364), SIMD4<Float>(1.00096, 0.145625, 0.717265, 0.702947)],
        [SIMD4<Float>(0.703675, 0.0114412, 0.678734, 0.682026), SIMD4<Float>(0.533131, 0.00318703, 0.643564, 0.64555), SIMD4<Float>(0.909029, 0.253042, 0.701864, 0.722334), SIMD4<Float>(0.479433, 0.0267344, 0.618775, 0.636102), SIMD4<Float>(1.22161, 0.00101504, 0.759651, 0.791392), SIMD4<Float>(2.29081, 0.182664, 0.758499, 0.771941), SIMD4<Float>(1.97737, 0.000605422, 0.713424, 0.729128), SIMD4<Float>(0.780427, 0.0570327, 0.670889, 0.679317)],
        [SIMD4<Float>(-0.57636, 0.100073, 0.984849, 0.447469), SIMD4<Float>(0.0200206, 0.960265, 0.990895, 0.993585), SIMD4<Float>(-3.82555, 0, 0.234472, 0), SIMD4<Float>(-4.70983, 0.0244164, 0.771949, 0.840926), SIMD4<Float>(-3.94831, 0.00085053, 0.867791, 0.895395), SIMD4<Float>(0.00764801, 0.911264, 0.978116, 0.987685), SIMD4<Float>(-3.60914, 0.0202963, 0.774058, 0.86957), SIMD4<Float>(-4.67985, 0.0253466, 0.772382, 0.836747)],
        [SIMD4<Float>(-3.0246, 0.10337, 0.905509, 0.0294604), SIMD4<Float>(-2.55056, 0.613564, 0.938252, 0.955991), SIMD4<Float>(-0.0206685, 0.843375, 0.988216, 0.796431), SIMD4<Float>(0.237545, 0.940296, 0.990285, 0.99323), SIMD4<Float>(-0.0289158, 0.885662, 0.988594, 0.991114), SIMD4<Float>(0.0327367, 0.869038, 0.975235, 0.985498), SIMD4<Float>(-1.45308, 0.148135, 0.932638, 0.00647244), SIMD4<Float>(-4.00619, 0.0763718, 0.831199, 0.876855)],
        [SIMD4<Float>(-0.474053, 0.0565018, 0.986379, 0.537058), SIMD4<Float>(-3.6397, 0.644797, 0.895682, 0.929424), SIMD4<Float>(-0.648268, 0.0867368, 0.995754, 0.463423), SIMD4<Float>(-3.9961, 0.578897, 0.860199, 0.907532), SIMD4<Float>(-3.60652, 0, 0.331115, 0), SIMD4<Float>(0.0043451, 0.926526, 0.979591, 0.988931), SIMD4<Float>(-2.11147, 0.156495, 0.896153, 0.0620189), SIMD4<Float>(-4.98863, 0.0202291, 0.739666, 0.818498)],
        [SIMD4<Float>(0.105471, 0.237953, 1, 0.494684), SIMD4<Float>(-0.0902385, 0.957814, 0.990394, 0.993309), SIMD4<Float>(-3.38166, 0.182502, 0.88026, 0.000122918), SIMD4<Float>(-4.71962, 0.0324721, 0.775506, 0.844803), SIMD4<Float>(-2.76659, 0.121787, 0.906632, 0.2463), SIMD4<Float>(-3.54201, 0.0186037, 0.789522, 0.872316), SIMD4<Float>(-2.1384, 0.00775972, 0.875344, 0.201299), SIMD4<Float>(-4.73035, 0.00786309, 0.770199, 0.836817)],
        [SIMD4<Float>(0.497275, 0.215882, 0.645161, 0.600277), SIMD4<Float>(0.305156, 0.0766034, 0.599288, 0.552949), SIMD4<Float>(0.236671, 0.0160531, 0.582236, 0.536589), SIMD4<Float>(0.213036, 0.0019512, 0.574114, 0.528712), SIMD4<Float>(0.984456, 0.00159929, 0.741886, 0.720927), SIMD4<Float>(1.39569, 0.00125099, 0.654029, 0.563752), SIMD4<Float>(1.28903, 0.0451735, 0.610023, 0.544638), SIMD4<Float>(0.476076, 0.209762, 0.61453, 0.571601)],
    ]
}
