// Generated by scripts/filmsim_bake.py — do not edit by hand.
// Ordered film/paper stocks for the spectral film simulation, plus the
// precomputed neutral enlarger balance per film×paper (optimised for this pipeline).
import simd

/// One selectable emulsion. `index` is the value handed to the kernel:
/// `film` (0..<paperOffset) for films, relative 0-based `paper` for papers.
public struct FilmStock: Sendable, Hashable, Identifiable {
    public let index: Int
    public let key: String
    public let name: String
    public let isPaper: Bool
    /// Reversal (slide) stock — best viewed via the scanned-positive path, not an RA4 print.
    public let isPositive: Bool
    public var id: String { (isPaper ? "paper:" : "film:") + key }
}

public enum FilmSimData {
    /// First paper's row block in FilmSim.lut; equals the film count.
    public static let paperOffset = 20

    public static let films: [FilmStock] = [
        FilmStock(index: 0, key: "kodak_ektar_100", name: "Kodak Ektar 100", isPaper: false, isPositive: false),
        FilmStock(index: 1, key: "kodak_portra_160", name: "Kodak Portra 160", isPaper: false, isPositive: false),
        FilmStock(index: 2, key: "kodak_portra_400", name: "Kodak Portra 400", isPaper: false, isPositive: false),
        FilmStock(index: 3, key: "kodak_portra_800", name: "Kodak Portra 800", isPaper: false, isPositive: false),
        FilmStock(index: 4, key: "kodak_portra_800_push1", name: "Kodak Portra 800 (Push 1)", isPaper: false, isPositive: false),
        FilmStock(index: 5, key: "kodak_portra_800_push2", name: "Kodak Portra 800 (Push 2)", isPaper: false, isPositive: false),
        FilmStock(index: 6, key: "kodak_gold_200", name: "Kodak Gold 200", isPaper: false, isPositive: false),
        FilmStock(index: 7, key: "kodak_ultramax_400", name: "Kodak Ultramax 400", isPaper: false, isPositive: false),
        FilmStock(index: 8, key: "kodak_vision3_50d", name: "Kodak Vision3 50D", isPaper: false, isPositive: false),
        FilmStock(index: 9, key: "kodak_vision3_250d", name: "Kodak Vision3 250D", isPaper: false, isPositive: false),
        FilmStock(index: 10, key: "kodak_vision3_200t", name: "Kodak Vision3 200T", isPaper: false, isPositive: false),
        FilmStock(index: 11, key: "kodak_vision3_500t", name: "Kodak Vision3 500T", isPaper: false, isPositive: false),
        FilmStock(index: 12, key: "fujifilm_pro_400h", name: "Fujifilm Pro 400H", isPaper: false, isPositive: false),
        FilmStock(index: 13, key: "fujifilm_xtra_400", name: "Fujifilm X-Tra 400", isPaper: false, isPositive: false),
        FilmStock(index: 14, key: "fujifilm_c200", name: "Fujifilm C200", isPaper: false, isPositive: false),
        FilmStock(index: 15, key: "kodak_ektachrome_100", name: "Kodak Ektachrome 100", isPaper: false, isPositive: true),
        FilmStock(index: 16, key: "kodak_kodachrome_64", name: "Kodak Kodachrome 64", isPaper: false, isPositive: true),
        FilmStock(index: 17, key: "fujifilm_provia_100f", name: "Fujifilm Provia 100F", isPaper: false, isPositive: true),
        FilmStock(index: 18, key: "fujifilm_velvia_100", name: "Fujifilm Velvia 100", isPaper: false, isPositive: true),
        FilmStock(index: 19, key: "kodak_verita_200d", name: "Kodak Verita 200D", isPaper: false, isPositive: false),
    ]

    public static let papers: [FilmStock] = [
        FilmStock(index: 0, key: "kodak_endura_premier", name: "Kodak Professional Endura Premier", isPaper: true, isPositive: false),
        FilmStock(index: 1, key: "kodak_ektacolor_edge", name: "Kodak Ektacolor Edge", isPaper: true, isPositive: false),
        FilmStock(index: 2, key: "kodak_supra_endura", name: "Kodak Professional Supra Endura", isPaper: true, isPositive: false),
        FilmStock(index: 3, key: "kodak_portra_endura", name: "Kodak Professional Portra Endura", isPaper: true, isPositive: false),
        FilmStock(index: 4, key: "fujifilm_crystal_archive_typeii", name: "Fujifilm Crystal Archive Type II", isPaper: true, isPositive: false),
        FilmStock(index: 5, key: "kodak_2383", name: "Kodak Vision 2383", isPaper: true, isPositive: false),
        FilmStock(index: 6, key: "kodak_2393", name: "Kodak Vision Premier 2393", isPaper: true, isPositive: false),
        FilmStock(index: 7, key: "kodak_ultra_endura", name: "Kodak Professional Ultra Endura", isPaper: true, isPositive: false),
    ]

    /// Neutral balance per [film][paper]: (printEV, filterC, filterM, filterY).
    static let neutralWB: [[SIMD4<Float>]] = [
        [SIMD4<Float>(0.334055, 0.00174542, 0.711305, 0.424006), SIMD4<Float>(0.374662, 2.7928e-05, 0.704592, 0.440655), SIMD4<Float>(0.630546, 0.159329, 0.727668, 0.544772), SIMD4<Float>(0.761363, 0.232688, 0.754846, 0.555136), SIMD4<Float>(1.05562, 1.69473e-05, 0.78518, 0.683782), SIMD4<Float>(1.64163, 6.91456e-06, 0.74737, 0.496709), SIMD4<Float>(1.89247, 9.99313e-06, 0.789761, 0.634408), SIMD4<Float>(0.659163, 0.255668, 0.733351, 0.475972)],
        [SIMD4<Float>(0.0772094, 0.00042204, 0.609477, 0.353766), SIMD4<Float>(0.303759, 0.116954, 0.636046, 0.444018), SIMD4<Float>(0.11551, 0.0520654, 0.576722, 0.39407), SIMD4<Float>(0.00576486, 0.00542781, 0.567326, 0.310717), SIMD4<Float>(0.814808, 0.0118591, 0.713006, 0.634773), SIMD4<Float>(1.3976, 0.00530235, 0.671441, 0.46694), SIMD4<Float>(1.559, 0.00577538, 0.704738, 0.596053), SIMD4<Float>(0.00555275, 0.0596213, 0.553971, 0.245881)],
        [SIMD4<Float>(-0.00496192, 0.158693, 0.552315, 0.391363), SIMD4<Float>(-0.358829, 0.00224422, 0.428543, 0.248716), SIMD4<Float>(-0.00891325, 0.228196, 0.501992, 0.410839), SIMD4<Float>(0.00372908, 0.243831, 0.521929, 0.378685), SIMD4<Float>(0.381153, 0.00237386, 0.601723, 0.564634), SIMD4<Float>(0.996933, 0.0178501, 0.554015, 0.380141), SIMD4<Float>(1.60207, 0.230056, 0.682887, 0.644249), SIMD4<Float>(0.0155138, 0.246274, 0.512064, 0.330862)],
        [SIMD4<Float>(0.670282, 0.195271, 0.72011, 0.623358), SIMD4<Float>(0.34701, 6.84919e-05, 0.647407, 0.540716), SIMD4<Float>(0.671413, 0.194383, 0.690375, 0.639238), SIMD4<Float>(0.27596, 0.00115662, 0.627057, 0.509348), SIMD4<Float>(1.60301, 0.285498, 0.821712, 0.810057), SIMD4<Float>(1.58977, 4.91322e-05, 0.706906, 0.58442), SIMD4<Float>(1.71658, 0.000287874, 0.733885, 0.672205), SIMD4<Float>(0.181441, 0.021256, 0.594562, 0.429237)],
        [SIMD4<Float>(1.13896, 0.292018, 0.763806, 0.652432), SIMD4<Float>(0.60004, 0.000629985, 0.663554, 0.51312), SIMD4<Float>(0.546458, 0.0002971, 0.636161, 0.516893), SIMD4<Float>(0.642291, 0.065546, 0.665566, 0.516519), SIMD4<Float>(1.30197, 3.73537e-05, 0.763954, 0.721481), SIMD4<Float>(1.89524, 0.0226041, 0.729843, 0.571075), SIMD4<Float>(1.99523, 0.00141756, 0.751336, 0.655355), SIMD4<Float>(0.408608, 0.00254342, 0.608603, 0.385547)],
        [SIMD4<Float>(0.742222, 2.43064e-05, 0.677144, 0.501097), SIMD4<Float>(0.7617, 0.000193686, 0.663473, 0.508548), SIMD4<Float>(1.04241, 0.174974, 0.697261, 0.604669), SIMD4<Float>(0.860945, 0.0960606, 0.676011, 0.529441), SIMD4<Float>(1.77056, 0.168678, 0.802122, 0.767717), SIMD4<Float>(2.03765, 0.00117924, 0.729911, 0.56086), SIMD4<Float>(2.17586, 0.000318644, 0.755638, 0.655476), SIMD4<Float>(0.572775, 1.2247e-06, 0.609542, 0.380984)],
        [SIMD4<Float>(0.00118284, 0.0228106, 0.553327, 0.367815), SIMD4<Float>(0.000365842, 0.0505037, 0.529225, 0.368414), SIMD4<Float>(0.00386022, 0.108413, 0.505971, 0.394655), SIMD4<Float>(-0.221977, 0.000734976, 0.465504, 0.260686), SIMD4<Float>(2.10231, 0.595005, 0.852543, 0.849802), SIMD4<Float>(1.21635, 3.23375e-06, 0.599832, 0.409185), SIMD4<Float>(1.4441, 0.00999013, 0.657289, 0.56206), SIMD4<Float>(0.145304, 0.185557, 0.544762, 0.355532)],
        [SIMD4<Float>(0.141421, 0.117477, 0.605672, 0.45341), SIMD4<Float>(0.195271, 0.16776, 0.595864, 0.472457), SIMD4<Float>(-0.00931667, 0.119278, 0.523841, 0.424478), SIMD4<Float>(-0.254184, 0.00279947, 0.47792, 0.288811), SIMD4<Float>(0.767997, 0.0944016, 0.691982, 0.672966), SIMD4<Float>(1.19588, 0.000506786, 0.618139, 0.443536), SIMD4<Float>(1.40965, 0.000354039, 0.67011, 0.585437), SIMD4<Float>(-0.00731528, 0.126084, 0.529765, 0.331779)],
        [SIMD4<Float>(-0.0285606, 0.446125, 0.547474, 0.464233), SIMD4<Float>(-1.02516, 0.222412, 0.182384, 0.0027243), SIMD4<Float>(-0.00043471, 0.627679, 0.496423, 0.490631), SIMD4<Float>(-0.975098, 0.350904, 0.186818, 0.0102713), SIMD4<Float>(-0.774834, 0.199992, 0.188395, 0.289959), SIMD4<Float>(0.328661, 0.0220291, 0.340098, 0.165166), SIMD4<Float>(0.604312, 3.97819e-05, 0.45496, 0.399719), SIMD4<Float>(-0.219378, 0.433467, 0.448912, 0.32877)],
        [SIMD4<Float>(-0.66664, 0.228024, 0.37919, 0.176404), SIMD4<Float>(-0.905813, 0.313498, 0.250923, 0.040279), SIMD4<Float>(-0.732056, 0.461486, 0.270932, 0.167602), SIMD4<Float>(-0.052367, 0.645734, 0.512756, 0.420274), SIMD4<Float>(-1.20861, 0.0539743, 0.00434032, 0.0666453), SIMD4<Float>(0.271858, 0.0361985, 0.330096, 0.115428), SIMD4<Float>(0.626796, 0.0606303, 0.468208, 0.396074), SIMD4<Float>(-0.807866, 0.241577, 0.272101, 0.00177207)],
        [SIMD4<Float>(-0.23006, 0.576939, 0.450992, 0.00333406), SIMD4<Float>(0.0880685, 0.7251, 0.511425, 0.183273), SIMD4<Float>(-0.117989, 0.729463, 0.41863, 0.109255), SIMD4<Float>(-0.169906, 0.72571, 0.426068, 0.0209063), SIMD4<Float>(-0.0228656, 0.654194, 0.405031, 0.269529), SIMD4<Float>(0.862608, 0.526176, 0.426243, 0.00588717), SIMD4<Float>(0.629686, 0.344748, 0.395117, 0.0109415), SIMD4<Float>(1.56868, 0.873927, 0.7861, 0.655345)],
        [SIMD4<Float>(1.86742, 0.885641, 0.832133, 0.755689), SIMD4<Float>(-0.289475, 0.653271, 0.380787, 0.00231577), SIMD4<Float>(-0.191401, 0.715606, 0.373672, 0.108749), SIMD4<Float>(0.206361, 0.779559, 0.512879, 0.262934), SIMD4<Float>(0.166583, 0.690223, 0.441283, 0.389293), SIMD4<Float>(0.841113, 0.514445, 0.400228, 0.0105184), SIMD4<Float>(0.622629, 0.333607, 0.376909, 0.016856), SIMD4<Float>(0.416548, 0.735766, 0.5613, 0.295562)],
        [SIMD4<Float>(-0.162632, 0.226495, 0.457632, 8.89709e-05), SIMD4<Float>(-0.160305, 0.300811, 0.431018, 0.0011484), SIMD4<Float>(-0.228562, 0.341562, 0.371675, 0.00113948), SIMD4<Float>(0.0163073, 0.436109, 0.465788, 0.0869307), SIMD4<Float>(0.000371193, 0.0700211, 0.411386, 0.257728), SIMD4<Float>(0.941274, 0.166728, 0.430275, 0.0243808), SIMD4<Float>(0.909248, 0.00431932, 0.455349, 0.155451), SIMD4<Float>(0.00966662, 0.363798, 0.459061, 0.000142691)],
        [SIMD4<Float>(0.807133, 0.0276048, 0.731828, 0.688323), SIMD4<Float>(0.820775, 0.169208, 0.720415, 0.688142), SIMD4<Float>(0.327305, 0.00431287, 0.603504, 0.594839), SIMD4<Float>(1.08764, 0.387465, 0.748583, 0.732846), SIMD4<Float>(0.9554, 8.46613e-05, 0.713085, 0.759104), SIMD4<Float>(2.02019, 0.00909829, 0.733623, 0.707826), SIMD4<Float>(2.28197, 0.00495656, 0.787404, 0.788185), SIMD4<Float>(0.647515, 0.0145889, 0.677571, 0.61554)],
        [SIMD4<Float>(0.934248, 0.12825, 0.74078, 0.73065), SIMD4<Float>(0.573327, 0.00261423, 0.667583, 0.661995), SIMD4<Float>(0.433835, 0.0143072, 0.613628, 0.643597), SIMD4<Float>(0.389096, 0.00149278, 0.617184, 0.610669), SIMD4<Float>(1.5216, 0.194185, 0.791918, 0.832599), SIMD4<Float>(2.23756, 0.170924, 0.750996, 0.769633), SIMD4<Float>(2.28415, 0.0652523, 0.776169, 0.810649), SIMD4<Float>(0.866938, 0.166313, 0.702782, 0.68641)],
        [SIMD4<Float>(-3.50268, 0.174626, 0.901138, 0), SIMD4<Float>(-4.66691, 0.0239355, 0.796529, 0.855927), SIMD4<Float>(-0.132726, 0.030124, 0.992516, 0.831383), SIMD4<Float>(-3.89715, 0.456655, 0.865548, 0.906499), SIMD4<Float>(-2.88941, 0.106075, 0.913539, 0), SIMD4<Float>(-3.57434, 0.0159104, 0.778184, 0.871266), SIMD4<Float>(-3.44896, 0.0142631, 0.808835, 0.902152), SIMD4<Float>(-2.71128, 0.631153, 0, 0.0692206)],
        [SIMD4<Float>(-3.27346, 0.101782, 0.205673, 2.9434e-05), SIMD4<Float>(-3.94249, 0, 0.858723, 0.891741), SIMD4<Float>(-3.19782, 0, 0.278927, 0.416091), SIMD4<Float>(-3.9154, 0.0278141, 0.853211, 0.887143), SIMD4<Float>(-1.83415, 0.230349, 0.9312, 0.682817), SIMD4<Float>(-2.95927, 0.01947, 0.835006, 0.894391), SIMD4<Float>(0.199874, 0.888023, 0.97992, 0.989353), SIMD4<Float>(-3.02898, 0.0848019, 0.90367, 0.41104)],
        [SIMD4<Float>(-0.606388, 0.0725803, 0.998129, 0.674552), SIMD4<Float>(-0.463278, 0, 0.999946, 0.739736), SIMD4<Float>(0.115961, 0.0871272, 0.994713, 0.870102), SIMD4<Float>(0.166584, 0.977039, 0.992341, 0.994561), SIMD4<Float>(-4.34913, 0.156144, 0.832351, 0.879318), SIMD4<Float>(-3.62034, 0.166319, 0.785737, 0.877171), SIMD4<Float>(-3.68612, 0.0141498, 0.794942, 0.894248), SIMD4<Float>(-0.249057, 0.00206904, 1, 0.755469)],
        [SIMD4<Float>(-0.698795, 0.0539214, 0.990077, 0.759973), SIMD4<Float>(-0.38568, 8.62483e-05, 0.993799, 0.810935), SIMD4<Float>(-0.447627, 0.119421, 0.991277, 0.792788), SIMD4<Float>(-4.69449, 0.0959083, 0.78986, 0.846239), SIMD4<Float>(-3.0194, 0, 0.856878, 0.709735), SIMD4<Float>(-3.60458, 0.0169621, 0.783704, 0.870795), SIMD4<Float>(0.184006, 0.919571, 0.982863, 0.991555), SIMD4<Float>(-2.39794, 0.623063, 0.985016, 0.0116307)],
        [SIMD4<Float>(0.362095, 0.139666, 0.632942, 0.559538), SIMD4<Float>(0.683209, 0.25208, 0.679011, 0.643378), SIMD4<Float>(0.165216, 0.00173854, 0.550147, 0.522275), SIMD4<Float>(0.139008, 0.00013962, 0.558084, 0.484065), SIMD4<Float>(0.920595, 6.42404e-06, 0.711301, 0.712212), SIMD4<Float>(1.35721, 0.00849065, 0.631751, 0.548164), SIMD4<Float>(1.72282, 0.178399, 0.702109, 0.695309), SIMD4<Float>(-0.0187381, 0.0197981, 0.500252, 0.378445)],
    ]
}
