// Generated by scripts/lcp_codegen.py — do not edit by hand.
// Adobe LCP lens-correction coefficients for the lenses we shoot, sampled at
// infinity focus. See LensCorrection.swift for the model and scripts/lcp_codegen.py
// for the source profiles. Radius is focal-length-normalised (r = sensorRadius/focal).
import simd

/// Lateral-CA radial model for one channel, relative to green.
struct CA: Sendable { let scale: Float; let k: SIMD3<Float> }
/// Vignette polynomial at one aperture: illumination = 1 + a·r² + a·r⁴ + a·r⁶.
struct VignetteSample: Sendable { let av: Float; let a: SIMD3<Float> }
/// One focal length's correction (a prime has a single sample; a zoom several).
struct FocalSample: Sendable {
    let focal: Float
    let distortion: SIMD3<Float>
    let caRed: CA
    let caBlue: CA
    let vignette: [VignetteSample]
}
/// An Adobe lens profile matched by focal range + max aperture (LENSMODEL is
/// unreliable on the SD14). `samples` are ordered by focal length.
struct LensProfile: Sendable {
    let name: String
    let isZoom: Bool
    let focalMin: Float
    let focalMax: Float
    let maxAperture: Float
    let samples: [FocalSample]
}

let lensProfiles: [LensProfile] = [
    LensProfile(
        name: "SIGMA 30mm F1.4 DC HSM A013", isZoom: false,
        focalMin: 30, focalMax: 30, maxAperture: 1.4,
        samples: [
            FocalSample(
                focal: 30, distortion: SIMD3<Float>(-0.144867, 0.114366, 0.152679),
                caRed: CA(scale: 1.00013, k: SIMD3<Float>(0.003793, -0.033854, 0.071467)),
                caBlue: CA(scale: 1.00043, k: SIMD3<Float>(-0.004181, 0.041671, -0.082648)),
                vignette: [VignetteSample(av: 0.970854, a: SIMD3<Float>(-6.43278, 35.0026, -87.4439)), VignetteSample(av: 2, a: SIMD3<Float>(-0.088128, -1.42859, -21.4046))]),
        ]),
    LensProfile(
        name: "SIGMA 70-300mm F4-5.6 DG MACRO", isZoom: true,
        focalMin: 70, focalMax: 300, maxAperture: 4,
        samples: [
            FocalSample(
                focal: 70, distortion: SIMD3<Float>(-0.142121, -0.055021, 0.152447),
                caRed: CA(scale: 0.999792, k: SIMD3<Float>(0.00245, 0.049392, -0.308495)),
                caBlue: CA(scale: 1.0005, k: SIMD3<Float>(-0.010153, 0.029455, 0.022224)),
                vignette: []),
            FocalSample(
                focal: 100, distortion: SIMD3<Float>(0.516063, 1.06201, 3.9668),
                caRed: CA(scale: 0.999719, k: SIMD3<Float>(0.003596, 0.177305, -2.54805)),
                caBlue: CA(scale: 1.00031, k: SIMD3<Float>(-0.017581, 0.040519, 1.99878)),
                vignette: []),
            FocalSample(
                focal: 135, distortion: SIMD3<Float>(1.53212, 4.03999, 18.1109),
                caRed: CA(scale: 0.999673, k: SIMD3<Float>(0.013546, -0.23756, -0.778109)),
                caBlue: CA(scale: 1.00006, k: SIMD3<Float>(-0.042688, 2.03997, -31.6029)),
                vignette: []),
            FocalSample(
                focal: 200, distortion: SIMD3<Float>(3.45137, 10.7702, 72.9591),
                caRed: CA(scale: 0.999771, k: SIMD3<Float>(0.002744, -0.816147, 24.7877)),
                caBlue: CA(scale: 0.999536, k: SIMD3<Float>(-0.000396, 1.56198, -84.9225)),
                vignette: []),
            FocalSample(
                focal: 300, distortion: SIMD3<Float>(6.16286, 19.9094, 300.151),
                caRed: CA(scale: 1.00001, k: SIMD3<Float>(-0.115738, 14.3488, -757.136)),
                caBlue: CA(scale: 0.999076, k: SIMD3<Float>(0.180387, -44.245, 4098.44)),
                vignette: []),
        ]),
]
