// Generated by scripts/noise_profile.py — do not edit by hand.
//
// Poisson-Gaussian noise model of the SD14 sensor, measured in the decoder's
// scene-linear sRGB output units at base sensitivity: var(x) = a + b·x per
// channel. Estimated registration-free from 86 dataset frames
// (Immerkær high-pass, per-bin MAD, weighted-median pooling; `a` floored at
// the 10-bit raw quantisation variance).

let sd14BaseNoise = NoiseProfile(
    a: SIMD3<Float>(4.543400e-05, 9.194510e-05, 7.649150e-05),
    b: SIMD3<Float>(4.662833e-04, 1.048266e-03, 2.120854e-03)
)
